version: '3'

services:
  db:
    platform: linux/amd64
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: whack
      MYSQL_DATABASE: whackus
    ports:
      - "3306:3306"
  web:
    image: cyra
    container_name: php_web
    depends_on:
      - db
    environment:
      DB_SERVER: db
      DB_PASSWORD: whack
      DB_NAME: whackus
    ports:
      - "8081:80"
    stdin_open: true
    tty: true
